name: Deploy frp server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy_frp_server.yml"
      - "frp_config/**"

# don't deploy if another deployment is in progress
# as it would be reading the same file system
concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: appleboy/ssh-action@25ce8cbbcb08177468c7ff7ec5cbfa236f9341e1
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ubuntu
          debug: true
          # TODO: do this via ansible instead
          script: |
            # Exit immediately if a command fails
            export FRP_TOKEN=${{ secrets.FRP_TOKEN }}
            set -e
            cd /home/ubuntu/frp-server
            git pull
            bash frp_config/setup_frp_server.sh
